### ISSUE TITLE
Issue with function(a,b,c)

### ISSUE THREAD

**Issue by tluyben** [felixhao28/JSCPP#1]
Any less than trivial program stops (for me) at 

        function(a, b, c) {
            return a.push(b).concat(c);
        },

where a is an Array, which, at least if you didn't do any magic to Array, would have a.push(b) return a number (the new length of the array) and then try to run .concat(c) on that number, which does not work. Am I doing something wrong? 

Way to reproduce: make a new C source with only; 

extern const byte title[];

and execute. I use the latest master jscpp_page.js file from github.

**Comment by felixhao28** [comment]
I am sorry extern keyword is not supported.

**Comment by felixhao28** [comment]
After reviewing the code, I realized you are right. I have posted the fix. Thanks for reporting.
