### ISSUE TITLE
stdlib.cpp test fails

### ISSUE THREAD

**Issue by nickkolok** [felixhao28/JSCPP#10]
grunt test output includes this: 

 1) cincout stdlib stdlib.cpp an error occurred:

      AssertionError: false == true
      + expected - actual

      -false
      +true
      
      at Context.<anonymous> (test/test.js:109:14)

  2) cincout stdlib stdlib.cpp should match expected output:

      AssertionError: expected '' to equal '1.234\n1234\n1234\n1234\n2\n1\n1234\n2\n1'
      + expected - actual

      +1.234
      +1234
      +1234
      +1234
      +2
      +1
      +1234
      +2
      +1
      
      at Context.<anonymous> (test/test.js:117:25)

**Comment by felixhao28** [comment]
On which commit did you find this issue? Or you can try pulling the latest one.

**Comment by nickkolok** [comment]
For example, 4d8bb25d36c2d81ee4865309e4ea457fef9f8e0f, or other:

nickolaus@nicknout:~/git/JSCPP$ git checkout 4508d2a0041bc1c0cbf91c31455c8f579d7d2ccc
Previous HEAD position was 4d8bb25... truncate negative when converting to unsigned
HEAD is now at 4508d2a... fix readme debugger example
nickolaus@nicknout:~/git/JSCPP$ grunt build test
Running "clean:build" (clean) task
>> 2 paths cleaned.

Running "copy:build" (copy) task
Created 2 directories, copied 1 file

Running "peg:build" (peg) task
Generating parser from "pegjs/ast.pegjs"...
Parser "lib/ast.js" generated in 194ms.
Generating parser from "pegjs/prepast.pegjs"...
Parser "lib/prepast.js" generated in 55ms.

Running "coffee:build" (coffee) task
>> 18 files created.

Running "browserify:dist" (browserify) task
>> Bundle dist/JSCPP.js created.

Running "mochaTest:test" (mochaTest) task


  cincout
    sample 0
      ✓ should match expected output
    A+B
      sample 0
        ✓ should match expected output
      loop
        sample 0
          ✓ should match expected output
        array
          sample 0
            ✓ should match expected output
          biginteger
            sample 0
              ✓ should match expected output
        maze
          sample 0
            ✓ should match expected output
        loop_control
          sample 0
            ✓ should match expected output
      binop
        sample 0
          ✓ should match expected output
        char_compare
          sample 0
            ✓ should match expected output
      function
        sample 0
          ✓ should match expected output
        string
          sample 0
            ✓ should match expected output
          sample 1
            ✓ should match expected output
      8bit
        sample 0
          ✓ should match expected output
        sample 1
          ✓ expected exception
          ✓ should match expected output
      unary
        sample 0
          ✓ should match expected output
    ifelse
      sample 0
        ✓ should match expected output
      sample 1
        ✓ should match expected output
      bubblesort
        sample 0
          ✓ should match expected output
    type_conversion
      sample 0
        ✓ should match expected output
    literal
      sample 0
        ✓ should match expected output
      maxWord
        sample 0
          ✓ should match expected output
    io
      sample 0
        ✓ should match expected output
      math
        sample 0
          ✓ should match expected output
    stdlib
      sample 0
        1) an error occurred
        2) should match expected output
    binary
      sample 0
        ✓ should match expected output


  25 passing (81ms)
  2 failing

  1) cincout stdlib sample 0 an error occurred:

      AssertionError: false == true
      + expected - actual

      -false
      +true
      
      at Context.<anonymous> (test/test.js:103:14)

  2) cincout stdlib sample 0 should match expected output:

      AssertionError: expected '' to equal '1.234\n1234\n1234\n1234\n2\n1\n1234\n2\n1'
      + expected - actual

      +1.234
      +1234
      +1234
      +1234
      +2
      +1
      +1234
      +2
      +1
      
      at Context.<anonymous> (test/test.js:110:23)



Warning: Task "mochaTest:test" failed. Use --force to continue.

Aborted due to warnings.
nickolaus@nicknout:~/git/JSCPP$

**Comment by felixhao28** [comment]
I have no idea why that fails on your side because it okay here. Could please run `node -harmony demo/debug -f test/stdlib.cpp` and see the detailed message on this exception?

**Comment by nickkolok** [comment]
nickolaus@nicknout:~/git/JSCPP$ node -harmony demo/debug -f test/stdlib.cpp

/home/nickolaus/git/JSCPP/lib/rt.js:118
    f = function*() {
                ^
SyntaxError: Unexpected token *
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/nickolaus/git/JSCPP/lib/launcher.js:3:12)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
nickolaus@nicknout:~/git/JSCPP$

**Comment by felixhao28** [comment]
@nickkolok What is your node version? The `function*()` syntax is for es6 generator functions and node supports it [from version 0.11](https://github.com/joyent/node/wiki/es6-(a.k.a.-harmony)-features-implemented-in-v8-and-available-in-node).

Then how about more specific `node --harmony_generators demo/debug -f test/stdlib.cpp`?

**Comment by nickkolok** [comment]
nickolaus@nicknout:~/git/JSCPP$ node --version
v0.10.33
nickolaus@nicknout:~/git/JSCPP$ node --harmony_generators demo/debug -f test/stdlib.cpp
Error: unrecognized flag --harmony_generators
Try --help for options

/home/nickolaus/git/JSCPP/lib/rt.js:118
    f = function*() {
                ^
SyntaxError: Unexpected token *
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/nickolaus/git/JSCPP/lib/launcher.js:3:12)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
nickolaus@nicknout:~/git/JSCPP$ 


Does it mean that some browsers will fail to execute some tests (and won't fail on others)?

**Comment by felixhao28** [comment]
You see, you're using node v0.10.33 and it does not support es6. I am working on transpiling it to a es5 version but meanwhile I suggest you upgrade your nodejs.

**Comment by felixhao28** [comment]
Now I have setup the transpiling for browserfied dist/JSCPP.js. So browsers other than Firefox and Chrome can run JSCPP now. However I still suggest you upgrade your nodejs for local execution.

**Comment by felixhao28** [comment]
If you don't know how to upgrade your nodejs or you need to keep the old version. I suggest you use [node version manager](https://github.com/creationix/nvm).
