### ISSUE TITLE
Error on matrix initialization

### ISSUE THREAD

**Issue by rodrigorgs** [felixhao28/JSCPP#109]
Consider the following code:

```c++
int main() {
    int matrix[2][2] = {{1, 2}, {3, 4}};
    return 0;
}
```

I should init the matrix with the values 1, 2, 3, and 4; however, the following error is issued: `2:5 dimensions do not agree, 2 != 2`

**Comment by felixhao28** [comment]
Indeed. It is now fixed on master branch.
