### ISSUE TITLE
grunt buils does not minify files

### ISSUE THREAD

**Issue by nickkolok** [felixhao28/JSCPP#13]
To use your wonderful library in production (yes, we are going to!), we should use minified files. Of course, we can minify any file ourself, but the fact that uglify task is mentioned in Gruntfile.js but not used is quite strange.

**Comment by felixhao28** [comment]
I tried to use uglifyjs but it does not seem to support ES6 syntax well.

I will continue to look into this issue when I have time.

**Comment by felixhao28** [comment]
A minified version is available now at dist/JSCPP.es5.min.js

**Comment by nickkolok** [comment]
Thanks a lot!
