### ISSUE TITLE
Add climits header

### ISSUE THREAD

**Issue by jassler** [felixhao28/JSCPP#144]
Would it be possible to add the `climits` / `limits.h` header library with the constants listed in the C++ reference?
https://www.cplusplus.com/reference/climits/

```C
CHAR_BIT
SCHAR_MIN
SCHAR_MAX
UCHAR_MAX
CHAR_MIN
CHAR_MAX
MB_LEN_MAX
SHRT_MIN
SHRT_MAX
USHRT_MAX
INT_MIN
INT_MAX
UINT_MAX
LONG_MIN
LONG_MAX
ULONG_MAX
LLONG_MIN
LLONG_MAX
ULLONG_MAX
```

I wanted to contribute with the idea of introducing a `src/includes/climits.ts` file that defines the constants somewhat like this.

```ts
/* eslint-disable no-shadow */
import { CRuntime } from "../rt";

export = {
    load(rt: CRuntime) {

        rt.defVar("INT_MAX", rt.intTypeLiteral, rt.val(rt.intTypeLiteral, rt.config.limits.int.max));
        rt.defVar("INT_MIN", rt.intTypeLiteral, rt.val(rt.intTypeLiteral, rt.config.limits.int.min));
        // ...

    }
};
```

The problem however is that those are variables that are introduced, not macros. As far as I can see there's no way to define simple macros in the `CRuntime`, unless I'm missing something.

**Comment by felixhao28** [comment]
> The problem however is that those are variables that are introduced, not macros.

Defining macros in JS is not well supported at the moment. Defining variables should work as the workaround most of the time.
