### ISSUE TITLE
srand()

### ISSUE THREAD

**Issue by nickkolok** [felixhao28/JSCPP#15]
In usual C++, srand() function is often used to really randomize rand() (or else rand() will return one random but fixed number - to help with debug).
In JSCPP, rand() returns different numbers each time. I don't know is it correct or not, but I'll be very glad if srand() function (maybe, empty?) will exist.

**Comment by felixhao28** [comment]
The rand function currently just calls `Math.random()` of JavaScript for better performance. And JavaScript random does not support seed.
I will write a pseudo random generation function.
