### ISSUE TITLE
[ Feature Request ] BrowserFS Integration

### ISSUE THREAD

**Issue by james-pre** [felixhao28/JSCPP#156]
I've been working on a project using JSCPP and [BrowserFS](https://github.com/jvilk/BrowserFS). I was wondering if we could get an integration where JSCPP FS calls get forwarded to BrowserFS. I'm open to doing it as a PR or writing my own integration though it would be great if it was officially supported.

**Comment by felixhao28** [comment]
Cool idea. I don't have time to work on it right now but please let me know if you need any support.
