### ISSUE TITLE
Javascript-defined classes

### ISSUE THREAD

**Issue by wvengen** [felixhao28/JSCPP#22]
Thanks for this great little interpreter!

I'd like to allow instantiation of a class defined in javascript. Even though it isn't supported, I'm curious to know what would roughly be needed to achieve this. Easy or hard? Any steps I'd need to take?

A simple include defining the _Foo_ class, would be (hope you're ok with ES6):

```js
// foo.js
export function load(rt) {
  const type = rt.newClass('Foo', []);

  const Foo = {
    t: type,
    v: {
      members: {},
    },
  };
  rt.scope[0]['Foo'] = Foo;

  rt.types[rt.getTypeSignature(Foo.t)] = {
    '#father': 'object',
  };
};
```

When instantiating an object with `Foo myFoo`, I get the error _No default value for object_.
Changing this to `Foo myFoo()` tells me _value is undefined_ in `CRuntime::cast`.

Would you be able to give any pointers?

**Comment by felixhao28** [comment]
What you might have seen in iostream.coffee is just my dirty hack to mock an object **instance**. The runtime engine is at like 0% readiness for maintaining object lifecycles. What you did in your code is to create a global instance called "Foo", name of whose class is "Foo".

**Comment by felixhao28** [comment]
In fact with some work [in the engine](https://github.com/felixhao28/JSCPP/blob/master/src/rt.coffee#L782), object initialization can be supported (while class definition still requires much more work on the syntax parser).

**Comment by felixhao28** [comment]
I just made a commit to support initializing a predefined class.

https://github.com/felixhao28/JSCPP/commit/b816618b9a7c871dd392a5e8b7864ed388832563

**Comment by wvengen** [comment]
Wow, thanks, I'm going to use this!!

**Comment by wvengen** [comment]
Looking good! Awesome. I hope this makes it into a new release some time soon.

**Comment by felixhao28** [comment]
I will probably make a new release when more support for classes is implemented, which will take quite a while. Meanwhile you can `npm install felixhao28/JSCPP` to use latest build.

**Comment by wvengen** [comment]
Ok, I'll wait :+1:
