### ISSUE TITLE
will implement cstdio scanf function

### ISSUE THREAD

**Issue by victorrseloy** [felixhao28/JSCPP#23]
as per CONTRIBUTE.md I'm creating this issue to let others know that I'm working on this.

The following functions from cstdio are uninplemented:

int getchar(void)
char *gets(char *str)
int putchar(int char)
int puts(const char *str)
int scanf(const char *format, ...)
int sscanf(const char *str, const char *format, ...)

I'll implement them.

**Comment by felixhao28** [comment]
Great thanks!
