### ISSUE TITLE
BUG: cstdio and cstring are conflicting.

### ISSUE THREAD

**Issue by victorrseloy** [felixhao28/JSCPP#24]
if you include cstdio and cstring on same cpp file you get an exception saying that some methods are already defined, this is happening because during the load of cstdio cstring is being implicit loaded by this line 

`rt.include "cstring"`

I've already started working on a fix to this, bellow follows a test case to see the problem happening:

```
#include <stdio.h>
#include <string.h>

int main()
{
    printf("test - ok");
    return 0;
}
```

**Comment by victorrseloy** [comment]
PR: #25 will fix this

**Comment by felixhao28** [comment]
Thanks! I will review your PR soon.
