### ISSUE TITLE
Request: Including pre-compiled "dist/JSCPP.js" into GitHub

### ISSUE THREAD

**Issue by MarkusBordihn** [felixhao28/JSCPP#27]
Very interesting project and good work.
It would be great if an pre-compiled "dist/JSCPP.js" version could be checked in into GitHub as well.
This makes the testing and integration with other project much easier, because the file could be simple include as library instead of compiling the hole project first.

Thanks and Greetings,
- Markus B.

**Comment by felixhao28** [comment]
Are you working with NodeJS or browser? If you are using NodeJS, you can run `npm install JSCPP`. If you are using browser, you can get a minified version here: (https://github.com/felixhao28/JSCPP/tree/gh-pages/dist)

**Comment by MarkusBordihn** [comment]
I'm working with NodeJS as kind of build system, but preferring the minified version for this use case. Thanks a lot.

**Comment by felixhao28** [comment]
I am not sure if you can use the minified file which is designed for browser on a NodeJS application (probably possible with webpack). And I honest don't know how to create a bundled and minified NodeJS version. Sorry.
