### ISSUE TITLE
8 bit types

### ISSUE THREAD

**Issue by billcollis** [felixhao28/JSCPP#3]
Hi Felix
I am beginning to look more deeply at your code and have begun integrating it into a javascript version of my microcontroller visualiser
I notice that the following does not work quite right,
int main()
{
    unsigned char x = 126; 
    x++;          //127
    x++;         //128
    x++;         //129
    x++;         //130
    x=x+1;       //result is       unknown:unknown overflow of 128(signed char)
    return 0;
}
// signed char does the same

I am very interested in 8 and 16 bit types as I would like to use this as the basis for a microcontroller simulator.
I see defaults.coffee handles the sizes of these, but in rt.coffee only 7bit char and 32bit ints appear to be used? I really do not understand your code so I am sorry i am not to be able to contribute to this very much at this stage.

thanks
Bill

**Comment by billcollis** [comment]
PS
I notice there is similar behaviour with unsigned short
int main()
{
    unsigned short x = 32766;
    x= x+10;    // overflow of 32776(short)
    return 0;
}

**Comment by felixhao28** [comment]
This is a bug confirmed. I looked into the reason and found that I wrongly promote unsigned types to signed types thus limiting the value range.

Thanks for reporting the bug.
