### ISSUE TITLE
Refactor the code into ES6 JS

### ISSUE THREAD

**Issue by felixhao28** [felixhao28/JSCPP#32]
I refactored code from ES5 JS to CoffeeScript a while ago because at that time ES6 is not that popular and without babel and eslint supporting ES6, CoffeeScript was much more appealing.

Now that ES6 JS is on par (actually surpassing) with CoffeeScript in terms of readability, maintanability and popularity. I think it is time to switch back to JS.

It is also a good opportunity to review and refactor the legacy code.

Update in 2020: Now Typescript is better than ES6 JS.

**Comment by alexandruionascu** [comment]
Could this help? 
https://github.com/decaffeinate/decaffeinate

**Comment by felixhao28** [comment]
Done, it is now written in TypeScript.
