### ISSUE TITLE
C++ to WebAssembly in a browser

### ISSUE THREAD

**Issue by photopea** [felixhao28/JSCPP#33]
I would like to make small chunks of my JS code faster (short functions, which perform heavy computation). I was thinking about writing them in WebAssembly manually, but writing them in C would be much more comfortable.

Would you like to extend your tool, so it can compile the C code into WebAssembly? I don't want to make a mess in my computer by installing heavy native compilers, just to translate several lines of C code into WebAssembly.

**Comment by felixhao28** [comment]
Maybe you can rewrite your JS code in asm.js?

> Would you like to extend your tool, so it can compile the C code into WebAssembly?

The project was built to be an interpreter. If you are looking for a compiler, it's better to start from the emscripten+LLVM approach. The main advantage of a JS-written package is that it can be run on client side, thus reducing server traffic/CPU time. And I don't see much gain from a JS-written compiler.

**Comment by photopea** [comment]
I am a web developer and I am not used to many native apps. The only two native apps I use is a web browser and a text editor. I think that the compiler inside a browser would be much more friendly to web developers, than some special apps controlled from a command line.

BTW. I think I found an online C++ to WASM compiler.

**Comment by felixhao28** [comment]
Cool. Do you mind sharing the online compiler? I'm interested.

**Comment by photopea** [comment]
Oh, sorry, I forgot to paste the URL :D  here it is https://wasdk.github.io/WasmFiddle/

**Comment by felixhao28** [comment]
I read its code and it is just a web client [calling an endpoint server for compilation](https://github.com/wasdk/WasmFiddle/blob/master/src/State.tsx#L28).
