### ISSUE TITLE
Pointers to arrays

### ISSUE THREAD

**Issue by billcollis** [felixhao28/JSCPP#35]
This code works fine , however the value of the ptr p_arr returned from the debugger, shows the array and not the value pointed to as per the attached image I would have expected the value of p_arr to display as ->11 
Looking at the code it seems to me that there is only a pointer type and not an array type, so arrays are subset of pointers?

![image](https://cloud.githubusercontent.com/assets/5107813/25676524/63dbfa5c-3096-11e7-9a49-8fcd9bb4e9f3.png)

**Comment by felixhao28** [comment]
I intentionally implemented array to keep its structural information, even referenced by a regular pointer. This helps checking boundary and debugging. To answer your question, yes I have implemented array type to be a special case of pointer.
