### ISSUE TITLE
Please add a minified/single file once every update

### ISSUE THREAD

**Issue by elpeleq42** [felixhao28/JSCPP#43]
I would like to ask if there could be published a single file/minified version of this lib with every update, because i'm trying to use it on the web, and installing/finding a way to unify the whole lib into a single file, using node, always causes problems to me, for some reason.

That if the online demo doesn't already use the last version avaliable(Could someone inform me about that?). In that case, I might just use it.

**Comment by alexandruionascu** [comment]
I confirm the issue, in Create-React-App for example it cannot be minified by the build script.

**Comment by felixhao28** [comment]
The online demo version (https://github.com/felixhao28/JSCPP/tree/gh-pages/dist) is basically the latest version.

**Comment by felixhao28** [comment]
I added the link to the readme.
