### ISSUE TITLE
short not overflowing

### ISSUE THREAD

**Issue by billcollis** [felixhao28/JSCPP#45]
Hi Felix
In the code below there should be an overflow as the type used is a short, but it appears that the calculation is done as an int?
thanks
Bill

```cpp
#include <iostream>
using namespace std;
#include <stdio.h>

unsigned short a = 900; //short is a 16bit type
unsigned char p =0;

int main() {
  p = (a*100)/1000;
  printf("a:%d\n",a);
  printf("p:%d\n",p);
  return 0;
}
```

**Comment by felixhao28** [comment]
I ran your code on http://cpp.sh/75ece and the output is 

```
a:900
p:90
```

My speculation is literal numbers are by default int and therefore `a * 100` gets promoted into int type.

**Comment by milahu** [comment]
```cpp
  p = (a*(unsigned short)(100))/(unsigned short)(1000);
```
fails with the error `overflow of 90000(unsigned short)`
but it should compile, even without warning, the overflow can be intentional

similar
```cpp
int main() {
  unsigned char x = 0;
  x--;
  return (int)(x != 255);
  // this returns bool type, not int type
}
```
fails with `overflow during post-decrement`

**Comment by felixhao28** [comment]
I understand that sometimes overflows on unsigned types are intentional, but it is my personal preference that overflow checks should be mandatory in JSCPP by default. I can add an option to turn the overflow checks off.

In my opinion, intentional overflows sacrifice readability for performance but performance is not a concern in JSCPP.

**Comment by milahu** [comment]
today i learned
1. expression overflow is undefined behavior
2. unsigned integer overflow is defined behavior as `out = (in).mod(2**numBits)`

[according to](https://stackoverflow.com/a/16188846/10440128) the C++ standard

> [3.9.1.4](https://timsong-cpp.github.io/cppwp/n3337/basic.fundamental#4) Unsigned integers, declared unsigned, shall obey the laws of arithmetic modulo 2^n where n is the number of bits in the value representation of that particular size of integer. [ footnote 46: This implies that unsigned arithmetic does not overflow because a result that cannot be represented by the resulting unsigned integer type is reduced modulo the number that is one greater than the largest value that can be represented by the resulting unsigned integer type. ]

> [6.8.1.2](https://timsong-cpp.github.io/cppwp/basic.fundamental#2) .... arithmetic for the unsigned type is performed modulo 2^N. [ Note: Unsigned arithmetic does not overflow. Overflow for signed arithmetic yields undefined behavior. — end note ]

> [7.1.4](https://timsong-cpp.github.io/cppwp/expr.pre#4) If during the evaluation of an expression, the result is not mathematically defined or not in the range of representable values for its type, the behavior is undefined. [ Note: Treatment of division by zero, forming a remainder using a zero divisor, and all floating-point exceptions varies among machines, and is sometimes adjustable by a library function. — end note ]

--

> I can add an option to turn the overflow checks off.

sounds good, similar to [llvm silence_unsigned_overflow](http://clang.llvm.org/docs/UndefinedBehaviorSanitizer.html#silencing-unsigned-integer-overflow)
ive added the `send_notice` function for that purpose in PR #60

**Comment by felixhao28** [comment]
@milahu I just pushed the fix. You can now use "unsigned_overflow" option (like this: https://github.com/felixhao28/JSCPP/blob/master/demo/debug.coffee#L15) to ignore overflows.

**Comment by felixhao28** [comment]
More specifically, it is:

```js
JSCPP.run(code, input, {
  unsigned_overflow: "ignore" // can also be "error" (default) or "warn"
})
```
