### ISSUE TITLE
bit invert ~  issue

### ISSUE THREAD

**Issue by billcollis** [felixhao28/JSCPP#6]
Hi Felix
been busy with other work, back to testing some code and found something not quite right with bit inversion,
noticed it first with this
```
unsigned char A=0;
unsigned char B=0x80;
int main() {
    A = ~B;
    return 0;
}
```
returns:   TypeError: type is undefined (also the error doesn't show a line number)

also this 
```
unsigned int A=0;
unsigned int B=0x0080;  //also B=0x80 or B=128;
int main() {
    A = ~B;
    return 0;
} 
```
returns:   4:5 cannot cast negative value to unsigned int

in defaults.coffee line 308 ...
```ret = ~l.v```
appears to invert everything using signed 64bit(?) int and therefore always thinks its a negative number

Also will you support binary literals 0b01010111 ?

thanks
Bill

**Comment by felixhao28** [comment]
Already fixed it in 4d8bb25. However bitwise operation followed by implicit type conversion is highly platform dependent and maybe this is worth emitting a warning (in the future).

Since binary literal is becoming a part of C++14, I can add support for this.
