### ISSUE TITLE
Function Prototypes

### ISSUE THREAD

**Issue by billcollis** [felixhao28/JSCPP#8]
Felix, have you / will you implemented function prototypes?
```
#include <iostream>

int func(int x);

int main() {
    int a = 10;
    int b = 0;    
    b = func(a);
    return 0;
}

int func(int x){
    //some code 
    return 2 * x;
}
```
tried this with the latest version of gh-pages
throws an error with function prototype both int func(int x); and int func(int);
error = 4:1 is interp really an array initialization?

thanks
Bill

**Comment by felixhao28** [comment]
It is essentially an interpreter of C++ so declaring a function with function prototypes are not really useful.

Nevertheless it should not throw an exception. I will fix that.
